# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

jobs:
  coding-standards:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          extensions: mbstring
          php-version: 8.3

      - run: composer validate --strict

  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          extensions: mbstring
          php-version: 8.3

      - run: composer install --no-interaction --no-progress --no-suggest

      - run: vendor/bin/phpstan analyse

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
        phpunit-version:
          - "^8"
          - "^9"
          - "^10"
        composer:
          - name: lowest
            arg: "--prefer-lowest --prefer-stable"
          - name: highest
            arg: "" # No args added as highest is default
        exclude:
          - php-version: "7.3"
            phpunit-version: "^10"
          - php-version: "7.4"
            phpunit-version: "^10"
          - php-version: "8.0"
            phpunit-version: "^10"
          - php-version: "8.1"
            phpunit-version: "^8"
          - php-version: "8.2"
            phpunit-version: "^8"
          - php-version: "8.3"
            phpunit-version: "^8"

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          extensions: mbstring
          php-version: ${{ matrix.php-version }}

      - run: >
          composer require
          phpunit/phpunit:${{ matrix.phpunit-version }}
          --no-interaction
          --prefer-dist
          --no-progress
          --update-with-all-dependencies
          ${{ matrix.composer.arg }}

      - run: vendor/bin/phpunit
